// ─────────────────────────────────────────────────────────────────────────────
// Transcript Generator — Creates HTML transcripts from ticket channels
// ─────────────────────────────────────────────────────────────────────────────

const logger = require('../../utils/logger');

/**
 * Fetches all messages from a channel (up to 500) and generates an HTML transcript.
 * @param {import('discord.js').TextChannel} channel - The ticket channel to transcribe
 * @returns {Promise<string>} The HTML transcript string
 */
async function generateTranscript(channel) {
  try {
    const messages = await fetchAllMessages(channel, 500);

    // Sort messages oldest first
    const sorted = messages.sort((a, b) => a.createdTimestamp - b.createdTimestamp);

    const html = buildHTML(channel, sorted);
    return html;
  } catch (err) {
    logger.error(`[Transcript] Error generating transcript for channel ${channel.id}: ${err.message}`);
    return buildHTML(channel, []);
  }
}

/**
 * Fetches messages from a channel in batches (Discord limits to 100 per request).
 * @param {import('discord.js').TextChannel} channel - The channel to fetch from
 * @param {number} limit - Maximum number of messages to fetch
 * @returns {Promise<import('discord.js').Message[]>} Array of messages
 */
async function fetchAllMessages(channel, limit) {
  const messages = [];
  let lastId = null;

  while (messages.length < limit) {
    const options = { limit: 100 };
    if (lastId) options.before = lastId;

    const batch = await channel.messages.fetch(options);
    if (batch.size === 0) break;

    messages.push(...batch.values());
    lastId = batch.last().id;

    if (batch.size < 100) break;
  }

  return messages.slice(0, limit);
}

/**
 * Builds the HTML transcript document.
 * @param {import('discord.js').TextChannel} channel - The channel
 * @param {import('discord.js').Message[]} messages - Sorted messages
 * @returns {string} HTML string
 */
function buildHTML(channel, messages) {
  const guildName = escapeHTML(channel.guild.name);
  const channelName = escapeHTML(channel.name);

  let messagesHTML = '';
  for (const msg of messages) {
    messagesHTML += buildMessageHTML(msg);
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Transcript — #${channelName}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #36393f; color: #dcddde; padding: 20px; }
    .header { background: #2f3136; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
    .header h1 { color: #fff; font-size: 1.4em; }
    .header p { color: #b9bbbe; font-size: 0.9em; margin-top: 5px; }
    .message { display: flex; padding: 8px 16px; margin: 4px 0; border-radius: 4px; }
    .message:hover { background: #32353b; }
    .avatar { width: 40px; height: 40px; border-radius: 50%; margin-right: 12px; flex-shrink: 0; background: #5865f2; display: flex; align-items: center; justify-content: center; color: #fff; font-weight: bold; font-size: 14px; }
    .avatar img { width: 40px; height: 40px; border-radius: 50%; }
    .content { flex: 1; }
    .author { font-weight: 600; color: #fff; margin-right: 8px; }
    .timestamp { color: #72767d; font-size: 0.75em; }
    .text { margin-top: 4px; line-height: 1.4; word-wrap: break-word; }
    .attachment { margin-top: 8px; }
    .attachment a { color: #00aff4; text-decoration: none; }
    .attachment a:hover { text-decoration: underline; }
    .bot-tag { background: #5865f2; color: #fff; font-size: 0.65em; padding: 2px 4px; border-radius: 3px; margin-left: 4px; vertical-align: middle; }
    .embed-block { border-left: 4px solid #5865f2; background: #2f3136; padding: 12px; margin-top: 8px; border-radius: 4px; }
    .footer { text-align: center; color: #72767d; margin-top: 20px; font-size: 0.85em; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${guildName} — #${channelName}</h1>
    <p>${messages.length} message(s) • Generated on ${new Date().toUTCString()}</p>
  </div>
  ${messagesHTML}
  <div class="footer">
    <p>Transcript generated by Antigravity Bot</p>
  </div>
</body>
</html>`;
}

/**
 * Builds HTML for a single message.
 * @param {import('discord.js').Message} msg - The message
 * @returns {string} HTML string for the message
 */
function buildMessageHTML(msg) {
  const author = escapeHTML(msg.author?.tag || 'Unknown User');
  const avatarURL = msg.author?.displayAvatarURL({ size: 64, extension: 'png' });
  const timestamp = msg.createdAt.toUTCString();
  const content = escapeHTML(msg.content || '');
  const isBot = msg.author?.bot;

  // Avatar element
  const avatarEl = avatarURL
    ? `<img src="${avatarURL}" alt="${author}">`
    : author.charAt(0).toUpperCase();

  // Bot tag
  const botTag = isBot ? '<span class="bot-tag">BOT</span>' : '';

  // Attachments
  let attachmentsHTML = '';
  if (msg.attachments && msg.attachments.size > 0) {
    for (const [, attachment] of msg.attachments) {
      const name = escapeHTML(attachment.name || 'attachment');
      attachmentsHTML += `<div class="attachment"><a href="${escapeHTML(attachment.url)}" target="_blank">📎 ${name}</a></div>`;
    }
  }

  // Embeds (simplified)
  let embedsHTML = '';
  if (msg.embeds && msg.embeds.length > 0) {
    for (const embed of msg.embeds) {
      const embedTitle = embed.title ? `<strong>${escapeHTML(embed.title)}</strong><br>` : '';
      const embedDesc = embed.description ? escapeHTML(embed.description) : '';
      embedsHTML += `<div class="embed-block">${embedTitle}${embedDesc}</div>`;
    }
  }

  return `
  <div class="message">
    <div class="avatar">${avatarEl}</div>
    <div class="content">
      <span class="author">${author}</span>${botTag}
      <span class="timestamp">${timestamp}</span>
      <div class="text">${content}</div>
      ${attachmentsHTML}
      ${embedsHTML}
    </div>
  </div>`;
}

/**
 * Escapes HTML special characters to prevent XSS.
 * @param {string} str - The string to escape
 * @returns {string} Escaped string
 */
function escapeHTML(str) {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

module.exports = { generateTranscript };
